/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.TrusteeRole;

import business.Employee.Employee;
import business.Enterprise.Enterprise;
import business.Enterprise.KivaEnterprise;
import business.Organization.TrusteeOrganization;
import business.UserAccount.UserAccount;
import business.WorkQueue.NewFieldPartnerWorkRequest;
import business.WorkQueue.NewLoanCaseWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kunal
 */
public class TrusteeWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer ;
    private KivaEnterprise business ;
    private UserAccount userAccount ;
    private Employee trustee ;
    /**
     * Creates new form TrusteeWorkAreaJPanel
     */
    public TrusteeWorkAreaJPanel() {
        initComponents();
    }

    public TrusteeWorkAreaJPanel(JPanel userProcessContainer, KivaEnterprise enterprise, UserAccount account, Employee trustee) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.business = enterprise ;
        this.userAccount = userAccount ;
        this.trustee = trustee ;
        
        populateBorrowerWorkTable();
        populateFieldPartnerWorkTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void populateBorrowerWorkTable()
    {
         DefaultTableModel model = (DefaultTableModel) tblBorrowerWorkCase.getModel();
         model.setRowCount(0);
         
         TrusteeOrganization trusteeOrg = business.getTrusteeOrganization();
         
         for(WorkRequest workRequest : trusteeOrg.getWorkQueue().getWorkRequestList())
         {
             if(workRequest instanceof NewLoanCaseWorkRequest)
                
             {NewLoanCaseWorkRequest nlcwr = (NewLoanCaseWorkRequest)workRequest;
                if(!nlcwr.getStatus().equals(NewLoanCaseWorkRequest.Status.Complete.getValue())){                
                   
                
                Object row [] = new Object[6];
                row[0] = nlcwr;
                row[1] = nlcwr.getLoan().getLoanCase().getCategory();
                row[2] = nlcwr.getLoan().getLoanCase().getLoanAmount();
                row[3] = nlcwr.getLoan().getLoanCase().getLoanLength();
                row[4] = nlcwr.getAnalyst().getName();
                if(nlcwr.getTrustee() != null)
                row[5] = nlcwr.getTrustee().getName();
                else
                row[5] = "";    
                model.addRow(row); 
             
                
                
             }}
                
         }
         
         
        
    }
    
    public void populateFieldPartnerWorkTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblFieldPartnerWorkCase.getModel();
        model.setRowCount(0);
        
        DefaultTableModel modelina = (DefaultTableModel) tblFieldPartnerWorkCase.getModel();
        model.setRowCount(0);
         
        TrusteeOrganization trusteeOrg = business.getTrusteeOrganization();
         
        for(WorkRequest workRequest : trusteeOrg.getWorkQueue().getWorkRequestList())
        {
            if(workRequest instanceof NewFieldPartnerWorkRequest)
            {
                NewFieldPartnerWorkRequest nfpwr = (NewFieldPartnerWorkRequest)workRequest;                
                if(!nfpwr.getStatus().equals(NewFieldPartnerWorkRequest.Status.Complete.getValue())){
                      
                
               
                Object row [] = new Object[6];
                row[0] = nfpwr;
                row[1] = nfpwr.getAnalyst().getName();
                row[2] = nfpwr.getPerformanceDetails().getRiskRating();
                row[3] = nfpwr.getStatus();
                row[4] = nfpwr.getAnalyst().getName();
                if(nfpwr.getTrustee() != null)
                row[5] = nfpwr.getTrustee().getName();
                else
                row[5] = "";                 
                model.addRow(row); 
             
            }}
                
        }
        
         
         
        
    }
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBorrowerWorkCase = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFieldPartnerWorkCase = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnViewDetails = new javax.swing.JButton();
        btnViewFieldPartnerDetails = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnViewKivaRevenue = new javax.swing.JButton();
        btnBorrowerAssignToMe = new javax.swing.JButton();
        btnFieldPartnerAssignToMe = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));

        tblBorrowerWorkCase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Borrower Name", "Category", "Loan Amount", "Loan Length", "Analyst", "Trustee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblBorrowerWorkCase);
        if (tblBorrowerWorkCase.getColumnModel().getColumnCount() > 0) {
            tblBorrowerWorkCase.getColumnModel().getColumn(0).setResizable(false);
            tblBorrowerWorkCase.getColumnModel().getColumn(1).setResizable(false);
            tblBorrowerWorkCase.getColumnModel().getColumn(2).setResizable(false);
            tblBorrowerWorkCase.getColumnModel().getColumn(3).setResizable(false);
            tblBorrowerWorkCase.getColumnModel().getColumn(4).setResizable(false);
            tblBorrowerWorkCase.getColumnModel().getColumn(5).setResizable(false);
        }

        tblFieldPartnerWorkCase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Name", "Analyst Name", "Risk Rating", "Status", "Analyst", "Trustee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblFieldPartnerWorkCase);
        if (tblFieldPartnerWorkCase.getColumnModel().getColumnCount() > 0) {
            tblFieldPartnerWorkCase.getColumnModel().getColumn(0).setResizable(false);
            tblFieldPartnerWorkCase.getColumnModel().getColumn(1).setResizable(false);
            tblFieldPartnerWorkCase.getColumnModel().getColumn(2).setResizable(false);
            tblFieldPartnerWorkCase.getColumnModel().getColumn(3).setResizable(false);
            tblFieldPartnerWorkCase.getColumnModel().getColumn(4).setResizable(false);
            tblFieldPartnerWorkCase.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  BORROWER WORK CASE  ");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  FIELD PARTNER WORK CASE  ");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        btnViewDetails.setBackground(new java.awt.Color(0, 0, 0));
        btnViewDetails.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnViewDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDetails.setText("VIEW DETAILS >>  ");
        btnViewDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnViewFieldPartnerDetails.setBackground(new java.awt.Color(0, 0, 0));
        btnViewFieldPartnerDetails.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnViewFieldPartnerDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnViewFieldPartnerDetails.setText("VIEW DETAILS >>");
        btnViewFieldPartnerDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnViewFieldPartnerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFieldPartnerDetailsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  TRUSTEE WORK AREA  ");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        btnViewKivaRevenue.setBackground(new java.awt.Color(0, 0, 0));
        btnViewKivaRevenue.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnViewKivaRevenue.setForeground(new java.awt.Color(255, 255, 255));
        btnViewKivaRevenue.setText("VIEW KIVA REVENUE COLLECTION >>");
        btnViewKivaRevenue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        btnViewKivaRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewKivaRevenueActionPerformed(evt);
            }
        });

        btnBorrowerAssignToMe.setBackground(new java.awt.Color(0, 0, 0));
        btnBorrowerAssignToMe.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnBorrowerAssignToMe.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrowerAssignToMe.setText("ASSIGN TO ME >>");
        btnBorrowerAssignToMe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnBorrowerAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowerAssignToMeActionPerformed(evt);
            }
        });

        btnFieldPartnerAssignToMe.setBackground(new java.awt.Color(0, 0, 0));
        btnFieldPartnerAssignToMe.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnFieldPartnerAssignToMe.setForeground(new java.awt.Color(255, 255, 255));
        btnFieldPartnerAssignToMe.setText("ASSIGN TO ME >>");
        btnFieldPartnerAssignToMe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnFieldPartnerAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFieldPartnerAssignToMeActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/karandutt/Documents/Java Swing/FINAL/KKL.jpeg")); // NOI18N
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBorrowerAssignToMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnViewFieldPartnerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFieldPartnerAssignToMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnViewKivaRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5)))
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrowerAssignToMe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewFieldPartnerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFieldPartnerAssignToMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(btnViewKivaRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(321, 321, 321))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewKivaRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewKivaRevenueActionPerformed
        // TODO add your handling code here:
        KivaRevenueCollectionJPanel krcjp = new KivaRevenueCollectionJPanel(this.userProcessContainer, this.business);
        userProcessContainer.add("KivaRevenueCollectionJPanel", krcjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewKivaRevenueActionPerformed

    private void btnBorrowerAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowerAssignToMeActionPerformed
        // TODO add your handling code here:
       DefaultTableModel model = (DefaultTableModel) tblBorrowerWorkCase.getModel();
       int selectedRow = tblBorrowerWorkCase.getSelectedRow();
       if(selectedRow < 0){
           JOptionPane.showMessageDialog(null,  "Please select a row first","Information", JOptionPane.INFORMATION_MESSAGE);
           return ;
       }
       else
       {
           NewLoanCaseWorkRequest nlcwr = (NewLoanCaseWorkRequest)tblBorrowerWorkCase.getValueAt(selectedRow, 0);
        // Check if it is already assigned
        if(nlcwr.getTrustee() != null){
            JOptionPane.showMessageDialog(null, "Trustee already assigned", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }           
           nlcwr.setTrustee(trustee);
       }
       
       JOptionPane.showMessageDialog(null,"Work request assigned", "Information", JOptionPane.INFORMATION_MESSAGE);
       populateBorrowerWorkTable();
    }//GEN-LAST:event_btnBorrowerAssignToMeActionPerformed

    private void btnFieldPartnerAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFieldPartnerAssignToMeActionPerformed
        // TODO add your handling code here:
        
       DefaultTableModel model = (DefaultTableModel) tblFieldPartnerWorkCase.getModel();
       int selectedRow = tblFieldPartnerWorkCase.getSelectedRow();
       if(selectedRow < 0){
           JOptionPane.showMessageDialog(null,  "Please select a row first","Information", JOptionPane.INFORMATION_MESSAGE);
           return ;
       }
       else
       {
           NewFieldPartnerWorkRequest nfpwr = (NewFieldPartnerWorkRequest)tblFieldPartnerWorkCase.getValueAt(selectedRow, 0);
        if(nfpwr.getTrustee() != null){
            JOptionPane.showMessageDialog(null, "Trustee already assigned", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }           
           nfpwr.setTrustee(trustee);
       }
       JOptionPane.showMessageDialog(null,"Work request assigned", "Information", JOptionPane.INFORMATION_MESSAGE); 
       populateFieldPartnerWorkTable();
    }//GEN-LAST:event_btnFieldPartnerAssignToMeActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        
       DefaultTableModel model = (DefaultTableModel) tblBorrowerWorkCase.getModel();
       int selectedRow = tblBorrowerWorkCase.getSelectedRow();
       if(selectedRow < 0)
       {
           JOptionPane.showMessageDialog(null, "Please select a row first","Information",  JOptionPane.INFORMATION_MESSAGE);
           return ;
       }
       else
       {
           NewLoanCaseWorkRequest nlcwr = (NewLoanCaseWorkRequest)tblBorrowerWorkCase.getValueAt(selectedRow, 0);
           if(nlcwr.getTrustee() != trustee){
           JOptionPane.showMessageDialog(null, "Please assign to yourself first", "Information", JOptionPane.INFORMATION_MESSAGE);
           return ;
        }
           
           TrusteeViewLoanCaseJPanel trusteeViewLoanCaseJPanel = new TrusteeViewLoanCaseJPanel(userProcessContainer,business,nlcwr);
           userProcessContainer.add("trusteeViewLoanCaseJPanel",trusteeViewLoanCaseJPanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
       }
        
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnViewFieldPartnerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFieldPartnerDetailsActionPerformed
        // TODO add your handling code here:
        
       DefaultTableModel model = (DefaultTableModel) tblFieldPartnerWorkCase.getModel();
       int selectedRow = tblFieldPartnerWorkCase.getSelectedRow();
       if(selectedRow < 0)
       {
           JOptionPane.showMessageDialog(null, "Please select a row first","Information",  JOptionPane.INFORMATION_MESSAGE);
           return ;
       }
       else
       {
           NewFieldPartnerWorkRequest nfpwr = (NewFieldPartnerWorkRequest)tblFieldPartnerWorkCase.getValueAt(selectedRow, 0);
           if(nfpwr.getTrustee() != trustee){
           JOptionPane.showMessageDialog(null, "Please assign to yourself first", "Information", JOptionPane.INFORMATION_MESSAGE);
           return ;
        }           
           
           TrusteeViewFieldPartnerJPanel trusteeViewFieldPartnerJPanel = new TrusteeViewFieldPartnerJPanel(userProcessContainer,business,nfpwr);
           userProcessContainer.add("trusteeViewFieldPartnerJPanel",trusteeViewFieldPartnerJPanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
       }
        
        
    }//GEN-LAST:event_btnViewFieldPartnerDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrowerAssignToMe;
    private javax.swing.JButton btnFieldPartnerAssignToMe;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton btnViewFieldPartnerDetails;
    private javax.swing.JButton btnViewKivaRevenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblBorrowerWorkCase;
    private javax.swing.JTable tblFieldPartnerWorkCase;
    // End of variables declaration//GEN-END:variables
}
