/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Nishant
 */
public class SignUpJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer ;
    private EcoSystem system ;
    /**
     * Creates new form SignUpJPanel
     */
    public SignUpJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.system = system ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSignUpBorrower = new javax.swing.JButton();
        btnSignUpLender = new javax.swing.JButton();
        btnBecomeFieldPartner = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSignUpBorrower.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnSignUpBorrower.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUpBorrower.setText("SIGN UP AS A BORROWER >>");
        btnSignUpBorrower.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        btnSignUpBorrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpBorrowerActionPerformed(evt);
            }
        });
        add(btnSignUpBorrower, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 480, 90));

        btnSignUpLender.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnSignUpLender.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUpLender.setText("SIGN UP AS A LENDER >>");
        btnSignUpLender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        btnSignUpLender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpLenderActionPerformed(evt);
            }
        });
        add(btnSignUpLender, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 480, 90));

        btnBecomeFieldPartner.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnBecomeFieldPartner.setForeground(new java.awt.Color(255, 255, 255));
        btnBecomeFieldPartner.setText("BECOME A FIELD PARTNER >>");
        btnBecomeFieldPartner.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        btnBecomeFieldPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBecomeFieldPartnerActionPerformed(evt);
            }
        });
        add(btnBecomeFieldPartner, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 480, 100));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  NOT YET ON KIVA?");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 416, -1));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 0, -1, 155));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 794, 430, 84));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 461, -1, 52));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/karandutt/Documents/Java Swing/FINAL/KKL.jpeg")); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBecomeFieldPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBecomeFieldPartnerActionPerformed
        // TODO add your handling code here:
        FieldPartnerFormJPanel fieldPartnerFormJPanel = new FieldPartnerFormJPanel(userProcessContainer, system);
        userProcessContainer.add("fieldPartnerFormJPanel", fieldPartnerFormJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);        
    }//GEN-LAST:event_btnBecomeFieldPartnerActionPerformed

    private void btnSignUpLenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpLenderActionPerformed
        // TODO add your handling code here:
        SignUpLenderJPanel signUpLenderJPanel = new SignUpLenderJPanel(userProcessContainer, system);
        userProcessContainer.add("signUpLenderJPanel", signUpLenderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);           
    }//GEN-LAST:event_btnSignUpLenderActionPerformed

    private void btnSignUpBorrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpBorrowerActionPerformed
        // TODO add your handling code here:
        SignUpBorrowerJPanel signUpBorrowerJPanel = new SignUpBorrowerJPanel(userProcessContainer, system);
        userProcessContainer.add("signUpBorrowerJPanel", signUpBorrowerJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);         
    }//GEN-LAST:event_btnSignUpBorrowerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBecomeFieldPartner;
    private javax.swing.JButton btnSignUpBorrower;
    private javax.swing.JButton btnSignUpLender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
